### ISSUE TITLE
[0.4.10] Docker - Please make sure you are using the server version of the FTB modpack!

### ISSUE THREAD

**Issue by Taubin** [NillerMedDild/Enigmatica6#2094]
**Modpack version**
0.4.10

**Describe the bug**
When attempting to start up the server using the docker container on init I receive the following error repeating in the logs

`Please make sure you are using the server version of the FTB modpack!`

Steps taken to run the server:
Download the server from forge, run the server on my local machine, copy configs defaultconfigs kubejs libraries mods and patchouli_books to the zip file
Copy the zip file to the directory on the server
Start the container

Docker-compose file:

```

version: '2'

# Repository for the image below: https://github.com/itzg/docker-minecraft-server

services:
    minecraft:
        image: itzg/minecraft-server:java8
        volumes:
            #  Uses the modpacks folder in the same folder as the docker-compose.yml for the server files to install
            - /mnt/cache/minecraft/modpacks/:/modpacks:ro
            #  Uses the data folder in the same folder as the docker-compose.yml for config, mods, world etc
            - /mnt/cache/minecraft/data:/data
        environment:
            EULA: 'true'
            TYPE: CURSEFORGE
            # The modpack zip you've downloaded from https://www.curseforge.com/minecraft/modpacks/enigmatica6/files
            CF_SERVER_MOD: /modpacks/Enigmatica6-0.4.10.zip
            # Default RAM allocation
            MEMORY: 8G
            OPS: taubin
        ports:
            - 25565:25565
        restart: unless-stopped
```

**Logs**
https://gist.github.com/Taubin/39a37598d234b0d2ee9d7f14c09c46ae

**Screenshots**
N/A

I'm not sure if this is an issue with the itzg server (which was updated 1 day ago apparently) or the server files I'm copying over. I apologize if this is just me being dumb but I believe I've done everything correctly.
