### ISSUE TITLE
Mod suggestion: XercaMod

### ISSUE THREAD

**Issue by AdamNisbett** [NillerMedDild/Enigmatica6#240]
This looks like it has a bunch of cool mechanics.  Don't know if any of them would cause problems integrating with other mods or not though.
https://www.curseforge.com/minecraft/mc-mods/xercamod
https://ercanserteli.com/xercamod/

**Comment by NillerMedDild** [comment]
Normally I'm against adding misc mods, but I'm intrigued, will have a look :)

**Comment by NillerMedDild** [comment]
It does have a bunch of nice features, I think it lacks JEI documentation and a bit of polish, but I'll add it. I will however turn a ton of things off:

```toml

#General settings
[general]
	#Enable Scythe
	scythe = true
	#Enable Confetti
	confetti = true
	#Enable Warhammer
	warhammer = true
	#Enable Golden Coins
	coins = false
	#Enable Grab Hook
	grab_hook = false
	#Enable Leather and Straw Blocks
	leather_straw = false
	#Enable Food
	food = false
	#Enable Tea
	tea = false
	#Enable Cushion
	cushion = true
	#Enable Courtroom Items
	courtroom = false
	#Enable Spyglass
	spyglass = true
	#Enable Bookcase
	bookcase = true
	#Enable Ender Flask
	flask = true
	#Enable Carved Wood
	carved_wood = true

```
